### ISSUE TITLE
直书（竖排）模式下的替换字符问题

### ISSUE THREAD

**Issue by dorawei** [aui/font-spider#110]
在书写模式为[直书（竖排）](https://www.w3.org/TR/css-writing-modes-3/#vertical-intro)时，font spider 不能正确生成直书模式下相对应的字符。

----

比如在下列设定下：

```CSS
html {
        writing-mode: vertical-rl;
        -webkit-writing-mode: vertical-rl;
        -epub-writing-mode: vertical-rl;
}

@font-face {
        font-family:"test";
        src:url(test.ttf);       
}

body {
        font-family:"test";
}
```

当使用原字体时，浏览器会显示正确的直书替换字符：

![使用原字体时](https://ooo.0o0.ooo/2016/10/03/57f244b884e01.png)

当使用 font spider 压缩后，此时显示的是默认的横书用字符：

![使用 font spider 压缩后](https://ooo.0o0.ooo/2016/10/03/57f244b8aca97.png)

----

### 直书替换字符的一些参考

比如默认时的`、`即U+3001 IDEOGRAPHIC COMMA 在直书下一般会被替换为 `︑ `(U+FE11)。

一些常见标点符号在字体中都有直书用替换字符：

![常见标点符号的直书用替换字符](https://ooo.0o0.ooo/2016/10/03/57f244b8801df.png)

还有部分日文字符等在直书时也要改变：

![日文字符直书变体](https://ooo.0o0.ooo/2016/10/03/57f244b892448.png)

**完整内容请参考：**
[Unicode® Technical Report #50 UNICODE VERTICAL TEXT LAYOUT](http://unicode.org/reports/tr50/)

----

关于字体的技术细节不太清楚，但其中应该会有直书模式的脚本或编码映射，所以希望 font spider 在压缩直书模式网页时能够支持正确的替换字符。

非常感谢~
