### ISSUE TITLE
运行font-spider命令失败

### ISSUE THREAD

**Issue by jinx92** [aui/font-spider#148]
目录

>★ 文件夹css
>>★ ★ font.css

>★ 文件夹font
>>★ ★  futurabqbook.ttf

>★ index.html

```html
<body>
	<div class="home">
		<h1>123456789</h1>
	</div>
</body>
```
```css
/*声明 WebFont*/
@font-face {
  font-family: 'pinghei';
  src: url('../font/futurabqbook.ttf');
  src:
    url('../font/futurabqbook.eot?#font-spider') format('embedded-opentype'),
    url('../font/futurabqbook.woff') format('woff'),
    url('../font/futurabqbook.ttf') format('truetype'),
    url('../font/futurabqbook.svg') format('svg');
  font-weight: normal;
  font-style: normal;
}
/*使用选择器指定字体*/
.home h1, .demo > .test {
    font-family: 'pinghei';
}
```
然后在当前文件里里面运行`font-spider  ./*.html` 出现 `<web font not found>`
