### ISSUE TITLE
多字重版本的字体处理不正确

### ISSUE THREAD

**Issue by idiotWu** [aui/font-spider#32]
比如我想同时引入 [kaigen-gothic](https://github.com/akiratw/kaigen-gothic) 的 `Regular` 和 `Bold` 版本，CSS 书写如下：

```css
@font-face {
  font-family: 'Kai Gen Gothic';
  src: url('../font/KaiGenGothicCN-Regular.eot');
  src:
    url('../fonts/KaiGenGothicCN-Regular.eot?#font-spider') format('embedded-opentype'),
    url('../fonts/KaiGenGothicCN-Regular.woff') format('woff'),
    url('../fonts/KaiGenGothicCN-Regular.ttf') format('truetype'),
    url('../fonts/KaiGenGothicCN-Regular.svg') format('svg');
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: 'Kai Gen Gothic';
  src: url('../font/KaiGenGothicCN-Bold.eot');
  src:
    url('../fonts/KaiGenGothicCN-Bold.eot?#font-spider') format('embedded-opentype'),
    url('../fonts/KaiGenGothicCN-Bold.woff') format('woff'),
    url('../fonts/KaiGenGothicCN-Bold.ttf') format('truetype'),
    url('../fonts/KaiGenGothicCN-Bold.svg') format('svg');
  font-weight: bold;
  font-style: normal;
}
```

但是只有后书写的规则会被识别，只生成了 `KaiGenGothicCN-Bold` 的子集。
