### ISSUE TITLE
以后的版本有希望压缩font awesome之类的图标字体么？

### ISSUE THREAD

**Issue by Voyga** [aui/font-spider#34]

**Comment by aui** [comment]
图标字体大多采用 `content` 属性实现，目前 font-spider 采用的是静态分析完成的字符抓取，对于伪元素的 `content` 属性支持不好，无法分析继承的字体。

解决方案是在运行环境来进行查询操作，例如 jsdom。

优点：精确
缺点：性能低下

以上方案正在评估中。

**Comment by junmer** [comment]
@aui 是否需要 fontmin 支持 按 name 查找

**Comment by aui** [comment]
@junmer 

按 name 查找？没明白这里。。

我继续说下 font-spider 爬虫的两个方案：

## 静态分析

这是 v0.2 版本开始采用的方案。icon 图标字体的选择器大部分使用如下伪类：

```css
[class^="icon-"], [class*=" icon-"] {
     font-family: 'icon';
     /*more code..*/
}
.icon-menu:after {
    content: 'a';
}
```

我拿到了 `[class^="icon-"], [class*=" icon-"]` 并不能查询到 `:after` 里面的 `content` 属性（内部使用 `cheerio` 模拟 `document.querySelectorAll`，哪怕原生 DOM API 也不支持  `:after` 查找） 。

如果继续深入分析 css 去查找 `:after` 伪节点所继承的字体，难度比较高。

## DOM 环境

在浏览器中可以直接使用如下 API 拿到 CSS `content` 属性：

```
var selector = '[class^="icon-"], [class*=" icon-"]';
var content = window.getComputedStyle(selector, ':after').getPropertyValue('content')
```

要在 NodeJS 中使用上述 API，那么需要构建完整的 DOM，目前已知的库有 jsdom 或者 PhantomJS（事实上 font-spider 第一个版本就是采用的 jsdom）。采用 DOM 的 API 查找字体与节点可以获取到更为精确的结果。
